add a wrapper script

diff --git a/.github/workflows/link-check.yaml b/.github/workflows/link-check.yaml
--- a/.github/workflows/link-check.yaml
+++ b/.github/workflows/link-check.yaml
@@ -14,5 +14,15 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - uses: actions/checkout@v4
-      - name: run muffet filer
-        run: ./.muffet-filter/muffet-filter -i ./.muffet-filter/ignores.json https://bhamail.github.io/picapsule/
+      - name: verify muffet filter wrapper is found
+        run: |
+          PROJECT_URL="https://github.com/bhamail/muffet-filter"
+          WRAPPER_FILENAME="mfw"
+          WRAPPER="./.muffet-filter/$WRAPPER_FILENAME"  
+          if test -f "$WRAPPER"; then
+            echo "using wrapper $WRAPPER"
+          else
+            echo "Missing muffet-filter wrapper file $WRAPPER. Download here: $PROJECT_URL" && exit 1
+          fi
+      - name: run muffet filter wrapper
+        run: ./.muffet-filter/mfw -i ./.muffet-filter/ignores.json https://bhamail.github.io/picapsule/
